---
- name: Install common
  hosts: all
  become: yes
  gather_facts: true
  vars:
    ansible_python_interpreter: /usr/bin/python2

  tasks:
    - name: Check packages
      package_facts:
        manager: auto

    - name: Install python 3.6 and epel-release
      ansible.builtin.yum:
        name:
          - python3
          - python3-pip
          - python3-devel
          - python3-libselinux
          - python3-setuptools
          - net-tools
          - epel-release
        state: present
      when: "'python3' or 'epel-release' not in ansible_facts.packages"

    - name: Set mydistribution
      ansible.builtin.set_fact:
        mydistribution: "{{ 'rhel' if (ansible_distribution == 'Red Hat Enterprise Linux') else (ansible_distribution | lower) }}"

    - name: Add signing key
      ansible.builtin.rpm_key:
        key: "https://download.docker.com/linux/{{ mydistribution }}/gpg"
        state: present
      when: "'docker-ce' not in ansible_facts.packages"

    - name: Add docker repository
      ansible.builtin.yum_repository:
        name: docker
        description: docker repository
        baseurl: "https://download.docker.com/linux/{{ mydistribution }}/$releasever/$basearch/stable"
        enabled: true
        gpgcheck: true
        gpgkey: "https://download.docker.com/linux/{{ mydistribution }}/gpg"
      when: "'docker-ce' not in ansible_facts.packages"

    - name: Install Docker
      ansible.builtin.yum:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: latest
        update_cache: true
      when: "'docker-ce' not in ansible_facts.packages"

    - name: Install docker-compose
      get_url:
        url : https://github.com/docker/compose/releases/download/1.29.2/docker-compose-linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: 'u+x,g+x'
      when: "'docker-ce' not in ansible_facts.packages"

    - name: Start Docker
      ansible.builtin.service:
        name: "docker"
        enabled: true
        state: started

    - name: Enable service Docker
      ansible.builtin.systemd:
        name: docker
        enabled: yes
        masked: no

    - name: Adding vagrant user to docker group
      ansible.builtin.user:
        name: vagrant
        groups: vagrant,docker
        append: yes

    - name: Upgrade all packages
      ansible.builtin.yum:
        name: '*'
        state: latest